version: 2
jobs:
  build:
    docker:
      # use the same docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/dockerapp

    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv dockerapp
            . dockerapp/bin/activate
            make install
            # install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
          
      - save_cache:
          paths:
            - ./dockerapp
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . dockerapp/bin/activate
            make lint
